### ISSUE TITLE
Update WSL instructions

### ISSUE THREAD

**Issue by liamdalg** [UoB-CSA/setup-guides#18]
It's a bit late now, but we should be recommending that people install WSL2 on Windows. Tilo's instructions are a bit outdated. WSL1 doesn't have a complete Linux kernel which means that tools like Delve don't work.

**Comment by RileyEv** [comment]
@ChrisGora @liamdalg can one of you look at this, i cant use WSL2 in a vm

**Comment by liamdalg** [comment]
I'll look at it later today. Perhaps we should have a brief description of what WSL actually *is*? Some students don't understand the separation between the VM and Windows.
