### ISSUE TITLE
VSCode setup guide incorrect

### ISSUE THREAD

**Issue by jackbondpreston** [UoB-CSA/setup-guides#8]
Pretty sure the VSCode guide doesn't seem correct any more. There is no Go extension by Microsoft that I can find, and it's definitely not the first one. I assume this needs to be changed to the Go extension provided by "Go team at Google" (https://marketplace.visualstudio.com/items?itemName=golang.Go#overview).

**Comment by ChrisGora** [comment]
> We just migrated from Microsoft/vscode-go

Yeah, looks like it. Which is good because the Microsoft one wasn't perfect.
