### ISSUE TITLE
Ubuntu 20.04 instructions

### ISSUE THREAD

**Issue by jackbondpreston** [UoB-CSA/setup-guides#9]
Given that AFAIK the required go version is  `>=1.13`, we should probably tell people using Ubuntu 20.04 to just run `apt install golang`, since this provides version `1.13.8` and is preferably to the `wget` method.

**Comment by ChrisGora** [comment]
It might be a little risky if people with older ubuntu don't read it properly and install older version of Go... But then I guess it's their fault

**Comment by RileyEv** [comment]
I lean to agreeing with Chris. It may be possible but people won't read and they'll end up with an old version of Go.

**Comment by jackbondpreston** [comment]
Simple solution to this is just to use `sudo apt install golang-1.14`, which will fail if the package is not available.

**Comment by ChrisGora** [comment]
Yeah that sounds good. They can fail early that way instead of installing the wrong thing.
